backend:
  name: git-gateway
  branch: main # or master, depending on your default branch
  roles: [admin, editor]

# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "bio"
    label: "Bio"
    folder: "content/bio"
    create: false
    format: "frontmatter"
    fields:
      - {
          label: "Bio Text",
          name: "bioText",
          widget: "text",
          hint: "Biography text",
        }

  - name: "contact"
    label: "Contact Information"
    folder: "content/contact"
    create: false
    format: "frontmatter"
    fields:
      - {
          label: "Discord",
          name: "discord",
          widget: "string",
          hint: "Discord invite link or username#1234",
        }
      - {
          label: "YouTube",
          name: "youtube",
          widget: "string",
          hint: "Full YouTube channel URL",
        }
      - {
          label: "Email",
          name: "email",
          widget: "string",
          hint: "Contact email address",
        }
      - {
          label: "Twitch",
          name: "twitch",
          widget: "string",
          hint: "Full Twitch channel URL",
        }
      - {
          label: "Twitter",
          name: "twitter",
          widget: "string",
          hint: "Full Twitter profile URL",
        }

  - name: "tournaments"
    label: "Tournaments"
    folder: "content/tournaments"
    create: true
    format: "frontmatter"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "tournament" }
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm",
          time_format: true,
        }
      - {
          label: "Prize Pool",
          name: "prizePool",
          widget: "number",
          hint: "Amount in dollars",
        }
      - { label: "Max Participants", name: "maxParticipants", widget: "number" }
      - {
          label: "Registration Open",
          name: "open",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Tournament URL",
          name: "url",
          widget: "string",
          required: false,
          hint: "Optional tournament registration link",
        }

  - name: "showmatches"
    label: "Showmatches"
    folder: "content/showmatches"
    create: true
    format: "frontmatter"
    summary: "{{fields.type}}: {{fields.date}}"
    fields:
      - {
          label: "Showmatch Type",
          name: "type",
          widget: "select",
          options: ["1v1", "2v2", "3v3"],
          default: "1v1",
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm",
          time_format: true,
        }
      - {
          label: "Prize Pool",
          name: "prizePool",
          widget: "number",
          hint: "Amount in dollars",
        }
    types:
      - label: "1v1 Showmatch"
        name: "1v1"
        fields:
          - label: "Team 1 Player"
            name: "team1_player"
            widget: "string"
          - label: "Team 2 Player"
            name: "team2_player"
            widget: "string"
      - label: "2v2 Showmatch"
        name: "2v2"
        fields:
          - label: "Team 1 Players"
            name: "team1_players"
            widget: "list"
            min: 2
            max: 2
            field: { label: "Player Name", name: "player", widget: "string" }
          - label: "Team 2 Players"
            name: "team2_players"
            widget: "list"
            min: 2
            max: 2
            field: { label: "Player Name", name: "player", widget: "string" }
      - label: "3v3 Showmatch"
        name: "3v3"
        fields:
          - label: "Team 1 Name"
            name: "team1_name"
            widget: "string"
          - label: "Team 1 Players"
            name: "team1_players"
            widget: "list"
            min: 3
            max: 3
            field: { label: "Player Name", name: "player", widget: "string" }
          - label: "Team 2 Name"
            name: "team2_name"
            widget: "string"
          - label: "Team 2 Players"
            name: "team2_players"
            widget: "list"
            min: 3
            max: 3
            field: { label: "Player Name", name: "player", widget: "string" }

  - name: "leaderboard"
    label: "Leaderboard"
    folder: "content/leaderboard"
    create: true
    format: "frontmatter"
    fields:
      - label: "Players"
        name: "leaderboardData"
        widget: "list"
        fields:
          - { label: "Player Name", name: "name", widget: "string" }
          - { label: "Wins", name: "wins", widget: "number" }

  - name: "timeline"
    label: "Timeline"
    folder: "content/timeline"
    create: true
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - { label: "Information", name: "info", widget: "text" }
